name: DevSecOps Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:
    
jobs:
  iac:
    runs-on: ubuntu-latest
    steps:
      - name: Clonar repositorio
        uses: actions/checkout@v3

      - name: Instalar Trivy
        run: |
          curl -sfL https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/install.sh | sh -s -- -b /usr/local/bin

      - name: Ejecutar Trivy para IaC (Generar informe JSON)
        run: |
          trivy fs . --exit-code 0 --severity LOW,MEDIUM,HIGH,CRITICAL --format json --output trivy-iac-report.json
          cat trivy-iac-report.json # Verificar el contenido del archivo

      - name: Enviar informe de Trivy a DefectDojo
        run: |
          if [ ! -f trivy-iac-report.json ]; then
            echo "El archivo trivy-iac-report.json no se generó correctamente"
            exit 1
          fi
          curl -X POST -v \
            -H "Authorization: Token ${{ secrets.DEFECTDOJO_API_KEY }}" \
            -H "Content-Type: application/json" \
            --form "engagement=${{ secrets.DEFECTDOJO_ENGAGEMENT_ID }}" \
            --form "scan_type=Trivy Scan" \
            --form "file=@trivy-iac-report.json" \
            --form "scan_date=$(date +%F)" \
            --form "active=true" \
            --form "verified=false" \
            --form "minimum_severity=Low" \
            "${{ secrets.DEFECTDOJO_URL }}/api/v2/import-scan/"

  sca:
    runs-on: ubuntu-latest
    steps:
      - name: Clonar repositorio
        uses: actions/checkout@v3

      - name: Configurar Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Instalar Maven
        run: sudo apt-get install -y maven

      - name: Ejecutar Dependency-Check (Generar informe JSON)
        run: |
          wget https://github.com/jeremylong/DependencyCheck/releases/download/v8.4.0/dependency-check-8.4.0-release.zip
          unzip dependency-check-8.4.0-release.zip
          ./dependency-check/bin/dependency-check.sh --project gestor-bancario --scan . --disableAssembly --format JSON --out dependency-check-report.json
          cat dependency-check-report.json # Verificar el contenido del archivo

      - name: Enviar informe de Dependency-Check a DefectDojo
        run: |
          if [ ! -f dependency-check-report.json ]; then
            echo "El archivo dependency-check-report.json no se generó correctamente"
            exit 1
          fi
          curl -X POST -v \
            -H "Authorization: Token ${{ secrets.DEFECTDOJO_API_KEY }}" \
            -H "Content-Type: application/json" \
            --form "engagement=${{ secrets.DEFECTDOJO_ENGAGEMENT_ID }}" \
            --form "scan_type=Dependency Check Scan" \
            --form "file=@dependency-check-report.json" \
            --form "scan_date=$(date +%F)" \
            --form "active=true" \
            --form "verified=false" \
            --form "minimum_severity=Low" \
            "${{ secrets.DEFECTDOJO_URL }}/api/v2/import-scan/"

  sast:
    runs-on: ubuntu-latest
    steps:
      - name: Clonar repositorio
        uses: actions/checkout@v3

      - name: Configurar Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Instalar Maven
        run: sudo apt-get install -y maven

      - name: Ejecutar análisis con SpotBugs (Generar informe XML)
        run: |
          cd PAI2_ST10 && mvn clean install -Ddependency-check.skip=true spotbugs:spotbugs
          cat PAI2_ST10/target/spotbugsXml.xml # Verificar el contenido del archivo

      - name: Enviar informe de SpotBugs a DefectDojo
        run: |
          if [ ! -f PAI2_ST10/target/spotbugsXml.xml ]; then
            echo "El archivo spotbugsXml.xml no se generó correctamente"
            exit 1
          fi
          curl -X POST -v \
            -H "Authorization: Token ${{ secrets.DEFECTDOJO_API_KEY }}" \
            -H "Content-Type: application/xml" \
            --form "engagement=${{ secrets.DEFECTDOJO_ENGAGEMENT_ID }}" \
            --form "scan_type=SpotBugs Scan" \
            --form "file=@PAI2_ST10/target/spotbugsXml.xml" \
            --form "scan_date=$(date +%F)" \
            --form "active=true" \
            --form "verified=false" \
            --form "minimum_severity=Low" \
            "${{ secrets.DEFECTDOJO_URL }}/api/v2/import-scan/"

  dast:
    runs-on: ubuntu-latest
    steps:
      - name: Clonar repositorio
        uses: actions/checkout@v3

      - name: Configurar Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Instalar Maven
        run: sudo apt-get install -y maven

      - name: Instalar dependencias
        run: |
          cd PAI2_ST10 && mvn clean install -DskipTests -Dspotbugs.skip=true -Ddependency-check.skip=true

      - name: Ejecutar OWASP ZAP DAST (Generar informe JSON)
        run: |
          docker run --rm -u root -v $(pwd):/zap/wrk -t zaproxy/zap-stable zap-full-scan.py \
            -t https://host.docker.internal:3343 \
            -J zap-report.json \
            -r zap-report.html
          cat zap-report.json # Verificar el contenido del archivo

      - name: Enviar informe de OWASP ZAP a DefectDojo
        run: |
          if [ ! -f zap-report.json ]; then
            echo "El archivo zap-report.json no se generó correctamente"
            exit 1
          fi
          curl -X POST -v \
            -H "Authorization: Token ${{ secrets.DEFECTDOJO_API_KEY }}" \
            -H "Content-Type: application/json" \
            --form "engagement=${{ secrets.DEFECTDOJO_ENGAGEMENT_ID }}" \
            --form "scan_type=ZAP Scan" \
            --form "file=@zap-report.json" \
            --form "scan_date=$(date +%F)" \
            --form "active=true" \
            --form "verified=false" \
            --form "minimum_severity=Low" \
            "${{ secrets.DEFECTDOJO_URL }}/api/v2/import-scan/"

  iast:
    runs-on: ubuntu-latest
    steps:
      - name: Clonar repositorio
        uses: actions/checkout@v3

      - name: Configurar Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Instalar Maven
        run: sudo apt-get install -y maven

      - name: Instalar dependencias
        run: |
          cd PAI2_ST10 && mvn clean install -DskipTests -Dspotbugs.skip=true -Ddependency-check.skip=true

      - name: Instalar Semgrep
        run: pip install semgrep

      - name: Ejecutar Semgrep (Generar informe SARIF)
        run: |
          semgrep --config=auto --exclude target --exclude .git . --sarif > semgrep-report.sarif
          cat semgrep-report.sarif # Verificar el contenido del archivo

      - name: Enviar informe de Semgrep a DefectDojo
        run: |
          if [ ! -f semgrep-report.sarif ]; then
            echo "El archivo semgrep-report.sarif no se generó correctamente"
            exit 1
          fi
          curl -X POST -v \
            -H "Authorization: Token ${{ secrets.DEFECTDOJO_API_KEY }}" \
            -H "Content-Type: application/json" \
            --form "engagement=${{ secrets.DEFECTDOJO_ENGAGEMENT_ID }}" \
            --form "scan_type=Semgrep JSON Report" \
            --form "file=@semgrep-report.sarif" \
            --form "scan_date=$(date +%F)" \
            --form "active=true" \
            --form "verified=false" \
            --form "minimum_severity=Low" \
            "${{ secrets.DEFECTDOJO_URL }}/api/v2/import-scan/"
